#!/usr/bin/env zsh

# Loop through {{ yadm.classes }} and create an alias for each
for class in {{ yadm.classes }}; do
  echo $class
  # Check for pseudo__<path>
  if [[ $class == pseudo__* ]]; then
    # Remove pseudo__ from the class name
    path=${class#pseudo__}
    alias ${class}="tu ${path} ${class}"
  fi
done