#!/usr/bin/env zsh

# Alias Shortcuts

# zshrc files
alias zrc="vi ${ZDOTDIR}/zshrc"
alias zrcl="vi ${ZDOTDIR}/zshrc.local"
alias sz="source ${ZDOTDIR}/zshrc"

# zsh_aliases files
alias za="vi ${ZDOTDIR}/zsh_aliases"
alias zal="vi ${ZDOTDIR}/zsh_aliases.local"

# zsh_exports files
alias ze="vi ${ZDOTDIR}/zsh_exports"
alias zel="vi ${ZDOTDIR}/zsh_exports.local"

# zsh_functions files
alias zf="vi ${ZDOTDIR}/zsh_functions"
alias zfl="vi ${ZDOTDIR}/zsh_functions.local"

# edit .ssh/config file
alias sc="vi ${HOME}/.ssh/config"

# vimrc
alias vm="vi ${MYVIMRC}"

# Tmux
alias tm="vi ${ZDOTDIR}/tmux.conf"
alias tx="tmux new -A -s"

# User stuff
alias cdu="cd $USER_HOME"

# Shortcut to edit the dotfiles
alias config="cd ${CONFIG_DIR}"

# This should be the last line of the file
# For local changes
# Don't make edits below this
[ -f "${ZDOTDIR}/zsh_aliases.local" ] && source "${ZDOTDIR}/zsh_aliases.local"
