#!/usr/bin/env zsh

# Alias Shortcuts

# Misc
alias vi="vim"

# zshrc files
alias zrc="vi ${GLOBAL_ZDOTDIR}/zshrc\#\#default"
alias zrcl="vi ${GLOBAL_ZDOTDIR}/zshrc"
alias zrcu="vi ${USER_ZDOTDIR}/zshrc"
alias sz="source ${USER_ZDOTDIR}/zshrc"

# zsh_aliases files
alias za="vi ${GLOBAL_ZDOTDIR}/zsh_aliases\#\#default"
alias zal="vi ${GLOBAL_ZDOTDIR}/zsh_aliases"
alias zau="vi ${USER_ZDOTDIR}/zsh_aliases"

# zsh_exports files
alias ze="vi ${GLOBAL_ZDOTDIR}/zsh_exports\#\#default"
alias zel="vi ${GLOBAL_ZDOTDIR}/zsh_exports"
alias zeu="vi ${USER_ZDOTDIR}/zsh_exports"

# zsh_functions files
alias zf="vi ${GLOBAL_ZDOTDIR}/zsh_functions\#\#default"
alias zfl="vi ${GLOBAL_ZDOTDIR}/zsh_functions"
alias zfu="vi ${USER_ZDOTDIR}/zsh_functions"

# edit .ssh/config file
alias sc="vi ${GLOBAL_DOTFILES}/ssh/config.d"
alias scu="vi ${USER_DOTFILES}/ssh/config.d"

# vimrc
alias vm="vi ${GLOBAL_DOTFILES}/vim/vimrc"

# git
alias gc="vi ${GLOBAL_DOTFILES}/git/gitconfig\#\#default"
alias gcl="vi ${GLOBAL_DOTFILES}/git/gitconfig"
alias gcu="vi ${USER_DOTFILES}/git/gitconfig"

# Tmux
# alias tmux='tmux new bash'
alias tm="vi ${USER_DOTFILES}/tmux/tmux.conf"
alias tx="tmux new -A -s"

# User stuff
alias cdu="cd ${USER_HOME}"

# Shortcut to edit the dotfiles
alias cdc="cd ${USER_CONFIG_DIR}"
alias cdd="cd ${USER_DOTFILES}"
alias cdz="cd ${USER_ZDOTDIR}"

# Global stuff
alias cdcg="cd ${GLOBAL_CONFIG_DIR}"
alias cddg="cd ${GLOBAL_DOTFILES}"
alias cdzg="cd ${GLOBAL_ZDOTDIR}"
alias zrcg="vi ${GLOBAL_ZDOTDIR}/zshrc.user"
alias zag="vi ${GLOBAL_ZDOTDIR}/zsh_aliases.user"
alias zeg="vi ${GLOBAL_ZDOTDIR}/zsh_exports.user"
alias zfg="vi ${GLOBAL_ZDOTDIR}/zsh_functions.user"
alias vmg="vi ${GLOBAL_DOTFILES}/vim/vimrc"
alias gcm="vi ${GLOBAL_DOTFILES}/git/gitconfig"

# Misc
alias tf="tput cnorm"
