#!/usr/bin/env zsh

# Source the shared profile
source ${DOTFILES}/profile

# Enable Powerlevel10k instant prompt. 
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Set the directory we want to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "${ZINIT_HOME}" ]; then
   mkdir -p "$(dirname ${ZINIT_HOME})"
   git clone https://github.com/zdharma-continuum/zinit.git "${ZINIT_HOME}"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add in zsh plugins
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zsh-users/zsh-syntax-highlighting

# Add in snippets
zinit snippet OMZP::git

# Load completions
autoload -Uz compinit && compinit

# zsh theme
# To customize prompt, run `p10k configure` or edit ~/.config/zsh/p10k.zsh.
[[ ! -f ${ZDOTDIR}/p10k.zsh ]] || source ${ZDOTDIR}/p10k.zsh
zinit ice depth=1; zinit light romkatv/powerlevel10k

# History
HISTSIZE=10000
HISTFILE=~/.zsh_history
SAVEHIST=${HISTSIZE}
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
bindkey '^ ' autosuggest-toggle               # ctrl+space will toggle autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8' # Appears light gray on black background

# By default, if you type in a directory and hit enter
# zsh will cd into that dir. I don't like that
unsetopt AUTO_CD

# Prepend the function path with the zsh completions functions
fpath=(/usr/local/share/zsh-completions $fpath)

# source other files
[ -f "${ZDOT_DIR}/zsh_functions" ] && source "${ZDOTDIR}/zsh_functions"
[ -f "${ZDOTDIR}/zsh_exports" ] && source "${ZDOTDIR}/zsh_exports"
[ -f "${ZDOTDIR}/zsh_aliases" ] && source "${ZDOTDIR}/zsh_aliases"

# For local changes
[ -f "${ZDOTDIR}/zshrc.local" ] && source "${ZDOTDIR}/zshrc.local"

# If a psuedo user is active, source its zshrc file
[ ! -z "${USER_HOME}" ] && [ -f "${USER_HOME}/zshrc.user" ] && source "${USER_HOME}/zshrc.user"

# Don't make edits below this

