#!/usr/bin/env zsh

export GLOBAL_DOTFILES=${GLOBAL_DOTFILES:-${HOME}/.dotfiles}
export USER_DOTFILES=${LOCAL_DOTFILES:-${GLOBAL_DOTFILES}}

export GLOBAL_CONFIG_DIR=${GLOBAL_CONFIG_DIR:-${HOME}/.config}
export USER_CONFIG_DIR=${LOCAL_CONFIG_DIR:-${GLOBAL_CONFIG}}

export GLOBAL_ZDOTDIR=${GLOBAL_ZDOTDIR:-${GLOBAL_DOTFILES}/zsh}
export USER_ZDOTDIR=${LOCAL_ZDOTDIR:-${GLOBAL_ZDOTDIR}}

source ${USER_ZDOTDIR}/zshrc
