#!/usr/bin/env sh

set -eu

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${0}.d"

if [ ! -d "$BOOTSTRAP_D" ]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
fi

bootstraps=""
while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ ~$ ]]; then
        bootstraps="$bootstraps $bootstrap"
    fi
done <<EOF
$(find -L "$BOOTSTRAP_D" -type f | sort)
EOF


for bootstrap in $bootstraps; do
    echo "\tExecuting $bootstrap..."
    if ! "$bootstrap"; then
        echo "Error: bootstrap '$bootstrap' failed" >&2
        exit 1
    fi
done

