#!/bin/bash

check_command() {
    return $(command -v $1 $ >/dev/null)
}

request_response() {
    printf "$1 "
    read response
}

confirm() {
    local prompt="${1:-Are you sure you want to continue? [Y/n]}"

    request_response "$prompt"
    case "$response" in
    [yY][eE][sS] | [yY] | "")
        return 0 # User confirmed, continue
        ;;
    *)
        return 1 # User canceled, exit with an error code
        ;;
    esac
}

# Clone the dotfiles repo using personal fork of yadm
yadm() {
    curl -sL https://raw.githubusercontent.com/AaronYoung5/yadm/refs/heads/develop/yadm | sh -s -- "$@"
}
yadm clone --recursive git@github.com:AaronYoung5/dotfiles.git --no-bootstrap $@ || exit 1

# If on darwin, ask if we wanna change scutil
if [[ "$OSTYPE" == "darwin"* ]]; then
    current_hostname=$(scutil --get HostName)
    # Check if user wants to change scutil
    if confirm "Do you want to change your computer's hostname from $current_hostname? [Y/n]"; then
        # Prompt for new hostname
        read -p "Enter new hostname: " new_hostname

        # Set the new hostname
        sudo scutil --set HostName "$new_hostname"
        echo "Hostname changed to $new_hostname"
    else
        echo "Hostname not changed."
    fi 
fi

# hostname is uname -n without domain stuff
hostname=$(uname -n | cut -d '.' -f 1)

# Create the default zshrc file
zshrc_file=${HOME}/.dotfiles/zsh/zshrc\#\#h.${hostname},!c.pseudo
if confirm "Create default zshrc? [Y/n]"; then
    touch $zshrc_file

    # Echo the content to the zshrc file
    echo "#!/usr/bin/env zsh" >> $zshrc_file
    echo "" >> $zshrc_file
    echo "# First source the default" >> $zshrc_file
    echo 'DIR="$(dirname "${0:A}")"' >> $zshrc_file
    echo 'source "$DIR/zshrc##default"' >> $zshrc_file
fi

# Finally alt and bootstrap
yadm alt

# Message
echo "All done! Run 'yadm bootstrap' to finish the setup process. You may need to restart your terminal."